{
  description = "Documentation site for ai-slop — agent skills for Claude Code";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { self, nixpkgs }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

      # `nix run` executes in whatever directory the caller is standing in, which
      # may be a subdirectory of the repo — or not the repo at all. Both dev
      # scripts start by locating the project root and failing clearly if there
      # isn't one, rather than generating content into someone's home directory.
      repoRoot = pkgs: pkgs.writeShellApplication {
        name = "repo-root";
        runtimeInputs = [ pkgs.git ];
        text = ''
          root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
          if [ -z "$root" ] || [ ! -f "$root/config.toml" ] || [ ! -d "$root/skills" ]; then
            echo "not inside the ai-slop repository (no config.toml + skills/ found)" >&2
            echo "clone it first: git clone https://github.com/calebstewart/ai-slop" >&2
            exit 1
          fi
          printf '%s\n' "$root"
        '';
      };

      # Top level rather than inside `packages` so `checks` can reuse it: a check
      # that ran against ./. directly would drag .git into the store and would
      # also see generated files that the real build never sees.
      src = builtins.path {
        path = ./.;
        name = "site-source";
        filter =
          path: type:
          let
            base = baseNameOf path;
            parent = baseNameOf (dirOf path);
          in
          !(builtins.elem base [
            ".git"
            ".github"
            "public"
            "result"
            "flake.nix"
            "flake.lock"
          ])
          # content/skills/ and static/files/ are generated by
          # scripts/generate-content.py (see .gitignore). Excluding them means a
          # stale local run can never leak into the published output — the
          # derivation always regenerates from skills/. Same reasoning as the
          # landing page excluding its locally-built static/resume.pdf.
          && !(type == "directory" && parent == "content" && base == "skills")
          && !(type == "directory" && parent == "static" && base == "files");
      };
    in
    {
      packages = forAllSystems (pkgs: rec {
        default = site;

        # content/skills/ is generated, so `zola serve` on its own would serve a
        # site with no skills in it — and would not notice edits under skills/,
        # because it watches content/. These two exist so nobody has to remember
        # that: `nix run` regenerates, then serves, then keeps regenerating.
        #
        # Real binaries rather than dev-shell shell functions, so they work from
        # `nix run` and show up in PATH inside `nix develop` identically.
        slop-gen = pkgs.writeShellApplication {
          name = "slop-gen";
          runtimeInputs = [
            pkgs.python3
            pkgs.git
            (repoRoot pkgs)
          ];
          text = ''
            # Assigned rather than inlined into cd: bash only propagates a command
            # substitution's failure to errexit when it is the whole assignment,
            # so `cd "$(repo-root)"` would print the error and carry on into `cd ""`.
            root=$(repo-root)
            cd "$root"
            exec python3 scripts/generate-content.py "$@"
          '';
        };

        slop-serve = pkgs.writeShellApplication {
          name = "slop-serve";
          runtimeInputs = [
            pkgs.zola
            pkgs.python3
            pkgs.git
            (repoRoot pkgs)
          ];
          text = ''
            # See the note in slop-gen: assigned, not inlined into cd, so a
            # failure to locate the repo actually stops the script.
            root=$(repo-root)
            cd "$root"

            python3 scripts/generate-content.py

            # zola serve watches content/, which is generated. This keeps an eye
            # on skills/, which is the actual source, and regenerates when it
            # changes — at which point zola picks the change up and reloads.
            # A generator error prints and is otherwise ignored, so a broken link
            # mid-edit does not take the preview server down with it.
            python3 - <<'WATCH' &
            import hashlib, os, subprocess, sys, time


            def snapshot():
                digest = hashlib.sha256()
                for root, dirs, files in os.walk("skills"):
                    dirs.sort()
                    for name in sorted(files):
                        path = os.path.join(root, name)
                        digest.update(path.encode())
                        digest.update(str(os.stat(path).st_mtime_ns).encode())
                return digest.hexdigest()


            previous = snapshot()
            while True:
                time.sleep(1)
                try:
                    current = snapshot()
                except OSError:
                    continue
                if current == previous:
                    continue
                previous = current
                print("skills/ changed - regenerating", flush=True)
                subprocess.run([sys.executable, "scripts/generate-content.py"], check=False)
            WATCH
            watcher=$!
            trap 'kill "$watcher" 2>/dev/null || true' EXIT INT TERM

            # base_url is rewritten to the bind address by `zola serve`, and the
            # templates derive the path prefix from it, so the preview is served
            # at / rather than /ai-slop/.
            zola serve "$@"
          '';
        };

        site = pkgs.stdenvNoCC.mkDerivation {
          pname = "ai-slop-site";
          version = "0.1.0";
          inherit src;

          nativeBuildInputs = [
            pkgs.zola
            pkgs.python3
          ];

          # The generator turns skills/*/SKILL.md + README.md into content/. It
          # runs here rather than being committed, so the skill files stay the
          # only copy of their own prose and the site cannot drift from them.
          buildPhase = ''
            runHook preBuild
            python3 scripts/generate-content.py
            zola build --output-dir ./public
            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall
            cp -r ./public $out
            runHook postInstall
          '';

          # The output is a website. Nothing in it is ever executed, and the raw
          # copies of bin/artisanal-slop and scripts/pr_status.py that the site
          # offers for download must keep the `#!/usr/bin/env ...` shebangs they
          # were written with — rewriting those to /nix/store paths would publish
          # a script nobody else can run.
          dontPatchShebangs = true;
        };
      });

      apps = forAllSystems (pkgs: rec {
        default = serve;

        serve = {
          type = "app";
          program = "${pkgs.lib.getExe self.packages.${pkgs.stdenv.hostPlatform.system}.slop-serve}";
          meta.description = "Regenerate content/ from skills/ and start the Zola preview server";
        };

        gen = {
          type = "app";
          program = "${pkgs.lib.getExe self.packages.${pkgs.stdenv.hostPlatform.system}.slop-gen}";
          meta.description = "Regenerate content/ from skills/ once and exit";
        };
      });

      # These are as much a linter for the skills as a check on the site. The
      # generator is the only thing between skills/ and what gets published, so
      # the invariants it depends on are worth failing a build over rather than
      # discovering as a missing page or a dead link.
      checks = forAllSystems (pkgs: {
        # Front matter, the name-matches-directory rule, required site metadata,
        # and every relative link in every README, SKILL.md and reference file.
        skills = pkgs.runCommand "check-skills" { nativeBuildInputs = [ pkgs.python3 ]; } ''
          cd ${src}
          python3 scripts/generate-content.py --check
          touch $out
        '';

        # A hand-written root-relative link is the one mistake that breaks in
        # production while looking fine locally: this is a project site served
        # under /ai-slop/, but `zola serve` serves at the root, so a literal
        # href="/style.css" would pass every local check and 404 once deployed.
        # Everything must go through the derived {{ prefix }}.
        template-links = pkgs.runCommand "check-template-links" { } ''
          cd ${src}
          if ${pkgs.gnugrep}/bin/grep -nE '(href|src)="/' templates/*.html; then
            echo
            echo "Root-relative link in a template. This site is served under a path"
            echo "prefix, so use {{ prefix }}/... instead — see templates/base.html."
            exit 1
          fi
          touch $out
        '';

        # The root README documents mode loss as a real failure mode for
        # artisanal-slop's driver, so make sure this repo is never the source of
        # it. Any bundled file the site offers as a raw download and that has a
        # shebang is expected to be executable.
        exec-bits = pkgs.runCommand "check-exec-bits" { nativeBuildInputs = [ pkgs.python3 ]; } ''
          cd ${src}
          python3 - <<'EOF'
          import pathlib, stat, sys
          bad = []
          for path in sorted(pathlib.Path("skills").rglob("*")):
              if not path.is_file() or path.suffix == ".md":
                  continue
              with path.open("rb") as handle:
                  if handle.read(2) != b"#!":
                      continue
              if not path.stat().st_mode & stat.S_IXUSR:
                  bad.append(path)
          for path in bad:
              print(f"{path}: has a shebang but is not executable (chmod +x)")
          sys.exit(1 if bad else 0)
          EOF
          touch $out
        '';

        # The templates derive the /ai-slop/ prefix from base_url, and GitHub
        # serves a project site at the repository name. If those two ever
        # disagree every internal link breaks, so assert they agree here.
        prefix = pkgs.runCommand "check-prefix" { nativeBuildInputs = [ pkgs.python3 ]; } ''
          cd ${src}
          python3 - <<'EOF'
          import sys, tomllib
          from urllib.parse import urlparse
          config = tomllib.load(open("config.toml", "rb"))
          path = urlparse(config["base_url"]).path.strip("/")
          repo = config["extra"]["repo"].split("/")[-1]
          if path != repo:
              print(f"base_url path {path!r} != repo name {repo!r}.")
              print("GitHub serves a project site at /<repo>/, and the templates derive")
              print("the link prefix from base_url, so these have to match.")
              sys.exit(1)
          EOF
          touch $out
        '';

        # Catches template errors, which none of the checks above would see.
        # Shares the derivation CI builds anyway, so it costs nothing there.
        site = self.packages.${pkgs.stdenv.hostPlatform.system}.site;
      });

      devShells = forAllSystems (pkgs: {
        default = pkgs.mkShell {
          # The same derivations `nix run` uses, so slop-serve behaves identically
          # whether you are in the dev shell or not. They were shell functions in
          # the shellHook once, which meant `serve` existed only inside the shell
          # and confusingly did not exist anywhere else.
          packages = [
            pkgs.zola
            pkgs.python3
            self.packages.${pkgs.stdenv.hostPlatform.system}.slop-serve
            self.packages.${pkgs.stdenv.hostPlatform.system}.slop-gen
          ];

          shellHook = ''
            echo "zola $(zola --version | cut -d' ' -f2)"
            echo "  slop-serve  regenerate content/ and preview at http://127.0.0.1:1111"
            echo "  slop-gen    regenerate content/ once"
          '';
        };
      });

      formatter = forAllSystems (pkgs: pkgs.nixfmt-tree);
    };
}
